spring:
  application:
    name: dagamer-mall-redis
  redis:
    host: 192.168.31.139
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

server:
  port: 8091